// <auto-generated />
namespace A3_EF6_Ext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddSprocforEmployeeInfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSprocforEmployeeInfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201501231823504_Add Sproc for EmployeeInfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
